on: [push]

jobs:
  whalescale:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: vbrown608/whalescale@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          defaultTag: "alpine:3.11"
