name: Image
on: [push]

jobs:
  whalescale:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Build Docker image
        run: docker build -t netlify/build:$GITHUB_SHA .
      - uses: vbrown608/whalescale@refactor/remove_redundant_catch
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          currentTag: netlify/build:${{ github.sha }}
          defaultTag: "alpine:3.11"
